# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96301eb828831b1e5c7a2990327bef894969b3ef7bdb7ff446030abc1126994a752d077bc680a0788762ed7f81779940d9aeae012e35300de1f88375b11b9916

test:
  secret_key_base: 44d10bda8f70df4cfae4d0656af3232812b06ff3742acda585181e64186836d07f6e3cc3611f1eeae4295151a182c62b986fb70f2f0e0bd7913568dd057c78da

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
